repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11
        args: [
          "--line-length", "80",
          "--target-version", "py311",
          "--include", "\.pyi?$",
          "--check",
          "--diff",
          "{{ cookiecutter.project_name }}/"
        ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages: [commit-msg]